opentelemetry-demo:
  # Jika Anda ingin menyambungkan ke Grafana Tempo milik Anda sendiri (di luar demo ini):
  # opentelemetry-collector:
  #   config:
  #     exporters:
  #       otlp:
  #         endpoint: "tempo-collector.monitoring.svc.cluster.local:4317"
  
  # Defaultnya semua komponen (Frontend, Jaeger/Tempo internal, Prometheus) akan menyala otomatis.
  components:
    frontend:
      enabled: true
  #    replicaCount: 1
    kafka:
      resources:
        limits:
          memory: 250Mi
        requests:
          memory: 100Mi

    # Kita potong juga untuk adservice & recommendation yang biasanya haus RAM
    adservice:
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 100Mi
          
    recommendationservice:
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 100Mi