opentelemetry-demo:
  # Jika Anda ingin menyambungkan ke Grafana Tempo milik Anda sendiri (di luar demo ini):
  # opentelemetry-collector:
  #   config:
  #     exporters:
  #       otlp:
  #         endpoint: "tempo-collector.monitoring.svc.cluster.local:4317"
  
  # Defaultnya semua komponen (Frontend, Jaeger/Tempo internal, Prometheus) akan menyala otomatis.
  components:
    frontend:
      enabled: true
  #    replicaCount: 1
  # 1. Hapus pembatasan global untuk komponen standar
  default:
    resources:
      limits: null
      requests: null

  # 2. override khusus untuk Kafka agar muat di memori kecil
  kafka:
    resources:
      limits:
        memory: 300Mi
      requests:
        memory: 100Mi
    # Mengubah env variable bawaan kafka di dalam pod
    env:
      - name: KAFKA_HEAP_OPTS
        value: "-Xmx128M -Xms128M"