apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-demo
  namespace: argocd # Namespace tempat Argo CD Anda terinstal
spec:
  project: default
  source:
    repoURL: 'https://github.com/ilyasjaelani/gitops-otel-demo.git' # URL Repo Anda
    targetRevision: main # Branch utama Anda
    path: otel-demo     # Folder tempat file values/kustomize Anda berada
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true